### ISSUE TITLE
Enable multiple register [Replace ReactOnRails?]

### ISSUE THREAD

**Issue by enzolutions** [Limenius/ReactBundle#21]
Hi, guys.

First things first, thank you for this awesome Bundle.

Now let me explain my ideas and issues.

Right now I am working on a page that requires N react components in the same web page, in the twig part it's easy because I could call N time the react_component.

The problems I cannot produce independent jsx files, because if I call more that one time, the second call will overwrite the Register since that is how ReactOnRails.register works more information  at  [https://github.com/shakacode/react_on_rails/issues/630](https://github.com/shakacode/react_on_rails/issues/630)

So, I have to pack all components in one bundle and register all of them in one register and works.

What is the problem with this approach, well usually I have common components like the menu, notifications, etc.; and only change the primary operation like edit user, etc.

Having components separated and registered independent allow the browser cache to have those components and be reused in a further request during user navigation, increasing the performance. Now I have a cache per page, which don't reuse the elements shared in different pages.

Let me know if you understand my scenery, and if you could recommend ma way to resolve. Maybe I am missing something obvious.

Kind regards

**Comment by nacmartin** [comment]
Hi, sorry for the late answer. Thanks for taking the time to report this.

I have been trying to understand and reproduce the behaviour you comment, but I couldn't. I have tried this https://github.com/nacmartin/symfony-react-sandbox/commit/27fcbe87eff93f227706cd490aa8fcbd6f6b7488 , to register several components, but I fail to see when the register is overwritten, since I can simply register several components.

Note that you can also register the components in separate javascript files. Example, here we import three files that import different components: https://github.com/nacmartin/symfony-react-sandbox/blob/enzo-problem/client/js/clientEntryPoint.js

Why am I understanding incorrectly about your problem?

**Comment by enzolutions** [comment]
I will check your example soon and let you know. thanks for your response.

**Comment by tetuaoro** [comment]
3 years later ... thank you very much :+1:  Work like a charm !
